const ARTBOARD_GROUP_CLASS_NAME = 'MSArtboardGroup';
const SYMBOL_INSTANCE_CLASS_NAME = 'MSSymbolInstance';
const SYMBOL_MASTER_CLASS_NAME = 'MSSymbolMaster';
const TEXT_LAYER_CLASS_NAME = 'MSTextLayer';

const LEGEND_CONTENT_NAME = '~LegendContent';
const LEGEND_BADGES_NAME = '~LegendBadges';
const LEGEND_WIDTH = 700;

const ACTIVE_LIB_NAME_SETTING = 'ActiveLibName';

const NONE = "None";

module.exports = {
  ARTBOARD_GROUP_CLASS_NAME,
  SYMBOL_INSTANCE_CLASS_NAME,
  SYMBOL_MASTER_CLASS_NAME,
  LEGEND_CONTENT_NAME,
  LEGEND_BADGES_NAME,
  LEGEND_WIDTH,
  ACTIVE_LIB_NAME_SETTING,
  TEXT_LAYER_CLASS_NAME,
  NONE
};
