const ARTBOARD_GROUP_CLASS_NAME = "MSArtboardGroup";
const SYMBOL_INSTANCE_CLASS_NAME = "MSSymbolInstance";
const SYMBOL_MASTER_CLASS_NAME = "MSSymbolMaster";

const LEGEND_ARTBOARD_NAME = '~Legend';
const LEGEND_ITEM_INDEX_NAME = '~LegendItemIndex';
const LEGEND_ARTBOARD_MIN_WIDTH = 300;

module.exports = {
  ARTBOARD_GROUP_CLASS_NAME,
  SYMBOL_INSTANCE_CLASS_NAME,
  SYMBOL_MASTER_CLASS_NAME,
  LEGEND_ARTBOARD_NAME,
  LEGEND_ITEM_INDEX_NAME,
  LEGEND_ARTBOARD_MIN_WIDTH
};