const ARTBOARD_GROUP_CLASS_NAME = 'MSArtboardGroup';
const SYMBOL_INSTANCE_CLASS_NAME = 'MSSymbolInstance';
const SYMBOL_MASTER_CLASS_NAME = 'MSSymbolMaster';

const LEGEND_ARTBOARD_NAME = '~Legend';
const LEGEND_BADGE_NAME = '~LegendBadge';

module.exports = {
  ARTBOARD_GROUP_CLASS_NAME,
  SYMBOL_INSTANCE_CLASS_NAME,
  SYMBOL_MASTER_CLASS_NAME,
  LEGEND_ARTBOARD_NAME,
  LEGEND_BADGE_NAME
};
