const ARTBOARD_GROUP_CLASS_NAME = 'MSArtboardGroup';
const SYMBOL_INSTANCE_CLASS_NAME = 'MSSymbolInstance';
const SYMBOL_MASTER_CLASS_NAME = 'MSSymbolMaster';

const LEGEND_ARTBOARD_NAME = '~Legend';
const LEGEND_GROUP_NAME = '~LegendGroup';

const WIX_STYLE_LIBRARY_NAME = 'Wix Style';
const ACTIVE_LIB_NAME_SETTING = 'ActiveLibName';

module.exports = {
  ARTBOARD_GROUP_CLASS_NAME,
  SYMBOL_INSTANCE_CLASS_NAME,
  SYMBOL_MASTER_CLASS_NAME,
  LEGEND_ARTBOARD_NAME,
  LEGEND_GROUP_NAME,
  WIX_STYLE_LIBRARY_NAME,
  ACTIVE_LIB_NAME_SETTING
};
